### PR TITLE
Update Nuget Packages to latest App Center nuget

### PR DESCRIPTION
**Pull request by LadderLogic**
Updating solution nuget packages.

### CODE REVIEW

**Comment by LadderLogic** [comment]
@MaximST92 @sdebruyn please review and merge if appropriate

**Comment by Axemasta** [comment]
+1 This would allow this sink to work in Serilog in Maui

**Comment by MaximST92** [comment]
We will address this.
First, we need some extra changes to the build setup.
We will keep you posted.

**Comment by JensSchadron** [comment]
I've updated the build pipelines just now.
@MaximST92 PR should be good for review now.

Also thank you @LadderLogic for your contribution.

**Review by MaximST92 — APPROVED** [review]

**Comment by sdebruyn** [comment]
Great work guys,  but I think I'm going to unsubscribe from this repo now sine it's been a while since I was involved here 🙃

**Pull request merged**
